= Documentation
:toc:
Matthew1471 <https://github.com/matthew1471[@Matthew1471]>;

// Document Settings:

// Set the ID Prefix and ID Separators to be consistent with GitHub so links work irrespective of rendering platform. (https://docs.asciidoctor.org/asciidoc/latest/sections/id-prefix-and-separator/)
:idprefix:
:idseparator: -

// Any code examples will be in Python by default.
:source-language: python

ifndef::env-github[:icons: font]

// Set the admonitions to have icons (Github Emojis) if rendered on GitHub (https://blog.mrhaki.com/2016/06/awesome-asciidoctor-using-admonition.html).
ifdef::env-github[]
:status:
:caution-caption: :fire:
:important-caption: :exclamation:
:note-caption: :paperclip:
:tip-caption: :bulb:
:warning-caption: :warning:
endif::[]

// Document Variables:
:release-version: 1.0
:url-org: https://github.com/Matthew1471
:url-repo: {url-org}/DrayTek-Tools
:url-contributors: {url-repo}/graphs/contributors

== Introduction

DrayTek-Tools is an unofficial project providing a collection of tools for DrayTek(R)'s products.

More details on the project are available from the xref:../README.adoc[project's homepage].

== DSL Status Broadcast Documentation

The DrayTek(R) Vigor(TM) DSL Status message broadcasts are encrypted using AES-128 in CBC mode, with a key derived from the first 5 bytes of the SHA-1 hash of the MAC address converted to a string of uppercase hexadecimal characters and padded with nulls.

This is probably best explained with an example, so given the following data:

MAC Address: `AA:BB:CC:DD:EE:FF`

Encrypted Payload (Bytes):

[source,text]
----
20 52 05 20 30 E2 58 4E 6D 7F 10 51 67 F7 A0 F4 DB 1E 92 1E 13 75 57 77 92 F5 2F E5 ED 4F 14 E1 77 22 D0 21 D3 77 0A A9 AF 3E 59 14 41 A9 EF 02 51 4C 4E 27 8E F5 70 1A 5E DE 03 6B 23 2F 94 BD 54 E3 B8 FE 45 15 CB 16 3D 78 A8 B2 F4 0D D9 80 F2 F4 84 1F 6C 96 79 B6 BF 4F 94 26 38 24 17 5B 2F 75 BF 6A 51 F9 C2 FB 02 95 90 F9 5F 39 CA 2D 9E FC 7E 4B
----

We will need to calculate the key to decrypt the data.

=== Calculating The Decryption Key and IV

. The 6 MAC address bytes (`AA BB CC DD EE FF`) are hashed using the SHA-1 algorithm to produce: `1B AC 77 B2 C9 4D 3C EE 1E C9 63 2B E6 51 C3 B6 8F 7A 78 BC`.

. The first 5 bytes of the SHA-1 digest are copied:
+
[options="header,autowidth"]
|=================================
|Position|  #1|  #2|  #3|  #4|  #5
|Value   |0x1B|0xAC|0x77|0xB2|0xC9
|=================================

. The 5 bytes are converted from raw bytes to a string of uppercase hexadecimal characters (1 byte is 2 ASCII characters) so they now actually occupy 10 bytes:
+
[options="header,autowidth"]
|===========================================================
|Position |  #1|  #2|  #3|  #4|  #5|  #6|  #7|  #8|  #9| #10
|Character|   1|   B|   A|   C|   7|   7|   B|   2|   C|   9
|Value    |0x31|0x42|0x41|0x43|0x37|0x37|0x42|0x32|0x43|0x39
|===========================================================

. AES-128 requires a 16 byte key and IV; so the remaining bytes are padded with nulls:
+
[options="header,autowidth"]
|===================================================================================
|Position |  #1|  #2|  #3|  #4|  #5|  #6|  #7|  #8|  #9| #10|#11|#12|#13|#14|#15|#16
|Character|   1|   B|   A|   C|   7|   7|   B|   2|   C|   9| \0| \0| \0| \0| \0| \0
|Value    |0x31|0x42|0x41|0x43|0x37|0x37|0x42|0x32|0x43|0x39|0x0|0x0|0x0|0x0|0x0|0x0
|===================================================================================

These 16 bytes are then used as both the key and the IV for the AES-128 algorithm in CBC mode.

=== Decoding The Binary Data

With the key calculated as above, the data can then start to be decrypted. To identify to the router a DSL Status broadcast, a protocol signature of `20 52 05 20` is used. It may also be used to determine the endian of the data as the first 2 bytes are the reverse of the second 2 bytes. These 4 bytes are not passed to the decryption algorithm and should be discarded.

After ignoring the first 4 bytes and running the AES-128 CBC decryption the decrypted payload is now:

[source,text]
----
\x010\xd7\x10\x04fkH\x00\x00\x0bm\x00\x00\x00\x00avg\xa0avg\xa0\x00\x00\x00\x06\x00\x00\x00\x00\x00\x00\x00\x03\x00\x00\x00\x03`C\x0e\x8c\x00\x83\xd6\x0112-3-2-3-0-5\x00\xff\xff\xff`2\xc8\x8817A\x00`\x94\x00\x00`\x93\xc5\xb0axg\xa0adSHOWTIME\x00\x00avg\xa0\x00\x00-\xb4\x00\x00\x00\x07a\x99\x00\x00
----

As you can see some of the strings are now visible. The data is stored in the following 112 fixed byte structure:

.DSL Status Message Structure
[options="header,autowidth"]
|================================================================
|Name                  |Type          |Length (bytes)
|DSL Upload Speed      |Signed Integer|4
|DSL Download Speed    |Signed Integer|4
|ADSL TX Cells         |Signed Integer|4
|ADSL RX Cells         |Signed Integer|4
|ADSL TX CRC Errors    |Signed Integer|4
|ADSL RX CRC Errors    |Signed Integer|4
|DSL Type              |Signed Integer|4
|Timestamp             |Signed Integer|4
|VDSL SNR Upload       |Signed Integer|4
|VDSL SNR Download     |Signed Integer|4
|ADSL Loop Attenuation |Signed Integer|4
|ADSL SNR Margin       |Signed Integer|4
|Modem Firmware Version|String        |20 (19 data + 1 null byte)
|Running Mode          |String        |18 (17 data + 1 null byte)
|State                 |String        |26 (25 data + 1 null byte)
|================================================================

[TIP]
====
Some of the meaning behind these values is best explained on the DrayTek(R) website pages link:https://www.draytek.co.uk/support/guides/kb-vigor-diagnostics-adsl-statistics[ADSL Statistics] and link:https://www.draytek.co.uk/support/guides/kb-dsl-status-more[How to check detailed ADSL / VDSL line statistics].
====

When unpacked into a tuple our sample data is:

[source]
----
(19978000, 73821000, 2925, 0, 1635149728, 1635149728, 6, 0, 3, 3, 1615007372, 8640001, b'12-3-2-3-0-5\x00\xff\xff\xff`2\xc8\x88', b'17A\x00`\x94\x00\x00`\x93\xc5\xb0axg\xa0ad', b'SHOWTIME\x00\x00avg\xa0\x00\x00-\xb4\x00\x00\x00\x07a\x99\x00\x00')
----
[NOTE]
====
Note the strings are null-terminated and the data after the null character is just uninitialised data from the device. Values which are not applicable (such as ADSL fields when the modem is running in VDSL mode) are also uninitalised.
====

Which ultimately results in the following:

[options="header,autowidth"]
|====================================================================
|Parameter             |Value
|DSL Upload Speed      |19978000 bps (19 Mbps)
|DSL Download Speed    |73821000 bps (73 Mbps)
|ADSL TX Cells         |2925
|ADSL RX Cells         |0
|ADSL TX CRC Errors    |1635149728
|ADSL RX CRC Errors    |1635149728
|DSL Type              |6 (1 = ADSL, 6 = VDSL)
|Timestamp             |0
|VDSL SNR Upload       |3
|VDSL SNR Download     |3
|ADSL Loop Attenuation |1615007372
|ADSL SNR Margin       |8640001
|Modem Firmware Version|b'12-3-2-3-0-5'
|Running Mode          |b'17A'
|State                 |b'SHOWTIME'
|====================================================================

[TIP]
====
Just because a DrayTek(R) device can send DSL Status broadcasts does not mean it has the capability to receive them. The Vigor(TM) 166 and 167 lack the capability to receive them as there is no Ethernet WAN port.
====